/*
 * Copyright 2026 Flamingock (https://www.flamingock.io)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.flamingock.core.processor.util;

import io.flamingock.internal.common.core.util.LoggerPreProcessor;

import javax.annotation.processing.ProcessingEnvironment;
import javax.tools.FileObject;
import javax.tools.JavaFileObject;
import javax.tools.StandardLocation;
import java.io.IOException;
import java.io.Writer;

/**
 * Persists a freshly-resolved {@link MetadataModuleIdentity}: writes the generated
 * {@code FlamingockMetadataProvider} source class via {@link javax.annotation.processing.Filer
 * #createSourceFile} and the SPI registration file via {@code Filer#createResource}.
 *
 * <p>The Filer disallows reopening a resource within the same javac invocation, so this
 * writer is idempotent only across builds — within one build, call it at most once for an
 * identity whose {@link MetadataModuleIdentity#isPersisted()} returns false.
 */
public final class MetadataProviderWriter {

    private MetadataProviderWriter() {
    }

    public static void write(ProcessingEnvironment processingEnv,
                             MetadataModuleIdentity identity,
                             LoggerPreProcessor logger) {
        writeProviderSource(processingEnv, identity, logger);
        writeSpiFile(processingEnv, identity, logger);
    }

    private static void writeProviderSource(ProcessingEnvironment processingEnv,
                                            MetadataModuleIdentity identity,
                                            LoggerPreProcessor logger) {
        String fqn = identity.getProviderClassFqn();
        try {
            JavaFileObject sourceFile = processingEnv.getFiler().createSourceFile(fqn);
            try (Writer writer = sourceFile.openWriter()) {
                writer.write(renderProviderSource(identity));
            }
            logger.verbose("Generated provider source: " + fqn);
        } catch (IOException e) {
            throw new RuntimeException("Failed to generate Flamingock provider source: " + fqn, e);
        }
    }

    private static void writeSpiFile(ProcessingEnvironment processingEnv,
                                     MetadataModuleIdentity identity,
                                     LoggerPreProcessor logger) {
        try {
            FileObject spiFile = processingEnv.getFiler().createResource(
                    StandardLocation.CLASS_OUTPUT, "",
                    MetadataModuleIdentity.SPI_FILE_PATH);
            try (Writer writer = spiFile.openWriter()) {
                writer.write(identity.getProviderClassFqn());
                writer.write(System.lineSeparator());
            }
            logger.verbose("Wrote SPI registration: " + MetadataModuleIdentity.SPI_FILE_PATH);
        } catch (IOException e) {
            throw new RuntimeException(
                    "Failed to write SPI registration file: " + MetadataModuleIdentity.SPI_FILE_PATH, e);
        }
    }

    private static String renderProviderSource(MetadataModuleIdentity identity) {
        String pkg = MetadataModuleIdentity.GENERATED_PACKAGE;
        String simpleName = identity.getProviderSimpleClassName();
        String resourcePath = identity.getMetadataResourcePath();
        return ""
                + "/* Generated by Flamingock annotation processor. Do not edit. */\n"
                + "package " + pkg + ";\n"
                + "\n"
                + "import io.flamingock.internal.common.core.metadata.FlamingockMetadataProvider;\n"
                + "\n"
                + "public final class " + simpleName + " implements FlamingockMetadataProvider {\n"
                + "    @Override\n"
                + "    public String getMetadataResourcePath() {\n"
                + "        return \"" + resourcePath + "\";\n"
                + "    }\n"
                + "}\n";
    }
}
